In [23]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [24]:
df = pd.read_csv("dataset_sucio.csv")

In [25]:
df.head()
df.info()
df.describe()
df.isnull().sum()
df.duplicated().sum()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_cliente      5000 non-null   int64
 1   nombre          5000 non-null   str
 2   genero          4940 non-null   str
 3   fecha_registro  5000 non-null   str
 4   gasto_q         4495 non-null   str
 5   ciudad          4843 non-null   str
 6   categoria       5000 non-null   str
dtypes: int64(1), str(6)
memory usage: 273.6 KB

np.int64(100)

In [26]:
df = df.drop_duplicates()

In [27]:
df.duplicated().sum()

np.int64(0)

In [28]:
df.isnull().sum()

id_cliente          0
nombre              0
genero             60
fecha_registro      0
gasto_q           497
ciudad            152
categoria           0
dtype: int64

In [29]:
df = df.dropna()

In [30]:
df_original = pd.read_csv("dataset_sucio.csv")

print("Filas originales:", df_original.shape[0])
print("Filas después de dropna:", df.shape[0])
print("Filas eliminadas:", df_original.shape[0] - df.shape[0])

Filas originales: 5000
Filas después de dropna: 4216
Filas eliminadas: 784

In [31]:
df.isnull().sum()

id_cliente        0
nombre            0
genero            0
fecha_registro    0
gasto_q           0
ciudad            0
categoria         0
dtype: int64

In [32]:
(df_original.shape[0] - df.shape[0]) / df_original.shape[0]

0.1568

In [33]:
df.head()
df.info()
df.describe()
df.isnull().sum()

<class 'pandas.DataFrame'>
Index: 4216 entries, 1 to 4999
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_cliente      4216 non-null   int64
 1   nombre          4216 non-null   str
 2   genero          4216 non-null   str
 3   fecha_registro  4216 non-null   str
 4   gasto_q         4216 non-null   str
 5   ciudad          4216 non-null   str
 6   categoria       4216 non-null   str
dtypes: int64(1), str(6)
memory usage: 263.5 KB

id_cliente        0
nombre            0
genero            0
fecha_registro    0
gasto_q           0
ciudad            0
categoria         0
dtype: int64

In [37]:
df['fecha_registro'] = pd.to_datetime(
    df['fecha_registro'],
    format='mixed',
    dayfirst=True,
    errors='coerce'
)

In [38]:
df['fecha_registro'].isnull().sum()
df['fecha_registro'].dtype
df.head()

,id_cliente,nombre,genero,fecha_registro,gasto_q,ciudad,categoria
1,500588,ANA DIAZ,f,2026-02-24,371.80,Villa Nueva,Services
2,502408,Maria Paz,m,2026-01-15,"373,33",quetzaltenango,retail
3,501688,Ana Mejia,f,2026-01-18,361.23,Quetzaltenango,Education
4,502916,Carlos Mendez,f,2026-01-29,"339,01",Amatitlan,Retail
5,504200,Oscar Rojas,m,2026-09-01,138.22,Antigua,RETAIL

In [42]:
df['gasto_q'] = df['gasto_q'].str.replace(',', '.', regex=False)

In [43]:
df['gasto_q'] = pd.to_numeric(df['gasto_q'])

In [44]:
df['gasto_q'].dtype
df['gasto_q'].isnull().sum()
df.describe()

,id_cliente,fecha_registro,gasto_q,anio,mes
count,4216.000000,4216,4216.000000,4216.0,4216.000000
mean,502461.639469,2026-03-11 08:35:44.971537,251.472389,2026.0,2.868596
min,500001.000000,2026-01-01 00:00:00,0.180000,2026.0,1.000000
25%,501249.750000,2026-01-22 00:00:00,125.432500,2026.0,1.000000
50%,502458.000000,2026-02-13 00:00:00,252.850000,2026.0,2.000000
75%,503691.250000,2026-02-28 00:00:00,378.392500,2026.0,2.000000
max,504900.000000,2026-12-02 00:00:00,499.860000,2026.0,12.000000
std,1416.090862,NaN,145.253119,0.0,2.912859

In [45]:
df.info()
df.head()

<class 'pandas.DataFrame'>
Index: 4216 entries, 1 to 4999
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_cliente      4216 non-null   int64
 1   nombre          4216 non-null   str
 2   genero          4216 non-null   str
 3   fecha_registro  4216 non-null   datetime64[us]
 4   gasto_q         4216 non-null   float64
 5   ciudad          4216 non-null   str
 6   categoria       4216 non-null   str
 7   anio            4216 non-null   int32
 8   mes             4216 non-null   int32
 9   mes_nombre      4216 non-null   str
dtypes: datetime64[us](1), float64(1), int32(2), int64(1), str(5)
memory usage: 329.4 KB

,id_cliente,nombre,genero,fecha_registro,gasto_q,ciudad,categoria,anio,mes,mes_nombre
1,500588,ANA DIAZ,f,2026-02-24,371.80,Villa Nueva,Services,2026,2,February
2,502408,Maria Paz,m,2026-01-15,373.33,quetzaltenango,retail,2026,1,January
3,501688,Ana Mejia,f,2026-01-18,361.23,Quetzaltenango,Education,2026,1,January
4,502916,Carlos Mendez,f,2026-01-29,339.01,Amatitlan,Retail,2026,1,January
5,504200,Oscar Rojas,m,2026-09-01,138.22,Antigua,RETAIL,2026,9,September

In [46]:
df['categoria'] = df['categoria'].str.lower().str.strip()
df['ciudad'] = df['ciudad'].str.lower().str.strip()
df['genero'] = df['genero'].str.lower().str.strip()

In [47]:
df.info()
df.head()

<class 'pandas.DataFrame'>
Index: 4216 entries, 1 to 4999
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_cliente      4216 non-null   int64
 1   nombre          4216 non-null   str
 2   genero          4216 non-null   str
 3   fecha_registro  4216 non-null   datetime64[us]
 4   gasto_q         4216 non-null   float64
 5   ciudad          4216 non-null   str
 6   categoria       4216 non-null   str
 7   anio            4216 non-null   int32
 8   mes             4216 non-null   int32
 9   mes_nombre      4216 non-null   str
dtypes: datetime64[us](1), float64(1), int32(2), int64(1), str(5)
memory usage: 329.4 KB

,id_cliente,nombre,genero,fecha_registro,gasto_q,ciudad,categoria,anio,mes,mes_nombre
1,500588,ANA DIAZ,f,2026-02-24,371.80,villa nueva,services,2026,2,February
2,502408,Maria Paz,m,2026-01-15,373.33,quetzaltenango,retail,2026,1,January
3,501688,Ana Mejia,f,2026-01-18,361.23,quetzaltenango,education,2026,1,January
4,502916,Carlos Mendez,f,2026-01-29,339.01,amatitlan,retail,2026,1,January
5,504200,Oscar Rojas,m,2026-09-01,138.22,antigua,retail,2026,9,September